# Generated by Django 6.0.8 on 2026-09-23 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. C Programming, Java Core, Python', max_length=100, unique=True)),
                ('code', models.CharField(help_text='e.g. C, JAVA, PYTHON, UNIX', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Course summary and learning objectives')),
                ('icon', models.CharField(default='Code2', help_text='Icon identifier for frontend UI', max_length=50)),
                ('color', models.CharField(default='#38bdf8', help_text='Hex color accent for the course card', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Topic name e.g. Pointers & Memory, Collections Framework', max_length=150)),
                ('description', models.TextField(blank=True, default='', help_text='Topic details and coverage')),
                ('order', models.IntegerField(default=0, help_text='Display order sequence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='questions.course')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('course', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default='Student', max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('passed', models.BooleanField(default=True)),
                ('answers_data', models.JSONField(default=list, help_text='Record of user selections, correctness, and explanations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='questions.course')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_results', to='questions.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the concept study guide', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Summary of what this concept covers')),
                ('content', models.TextField(blank=True, default='', help_text='Concept notes in editable Word/markdown text format')),
                ('file', models.FileField(blank=True, help_text='Optional uploaded PDF file', null=True, upload_to='study_materials/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='questions.course')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='questions.topic')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='The question problem statement or code snippet')),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], db_index=True, default='Easy', max_length=10)),
                ('option_a', models.TextField(help_text='Content for Option A')),
                ('option_b', models.TextField(help_text='Content for Option B')),
                ('option_c', models.TextField(help_text='Content for Option C')),
                ('option_d', models.TextField(help_text='Content for Option D')),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='A, B, C, or D', max_length=1)),
                ('explanation', models.TextField(blank=True, default='', help_text='Detailed explanation of the solution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.course')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
